language: php

php:
  - 5.6
  - 7.0
  - 7.1

before_script:
  - composer self-update
  - composer install --no-interaction --prefer-source --dev

script: VERBOSE=true ./vendor/bin/tester -c ./tests/php-unix.ini -j 40 ./tests
